name: Build .NET Project

on:
  workflow_call:
    inputs:
      project-name:
        description: 'Name of the project to build'
        required: true
        type: string
      project-path:
        description: 'Path to the project directory'
        required: true
        type: string
      project-type:
        description: 'Type of project (webapi, classlib, etc.)'
        required: true
        type: string
      dotnet-version:
        description: '.NET version to use'
        required: false
        type: string
        default: '8.0.x'
      build-configuration:
        description: 'Build configuration'
        required: false
        type: string
        default: 'Release'
      publish:
        description: 'Whether to publish the project'
        required: false
        type: boolean
        default: false
    outputs:
      build-success:
        description: 'Whether the build was successful'
        value: ${{ jobs.build.outputs.success }}
      artifacts-path:
        description: 'Path to build artifacts'
        value: ${{ jobs.build.outputs.artifacts-path }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.build.outputs.success }}
      artifacts-path: ${{ steps.build.outputs.artifacts-path }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for Nx affected detection

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Restore .NET dependencies
      run: npx nx g @nx-dotnet/core:restore

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Cache Nx
      uses: actions/cache@v4
      with:
        path: .nx/cache
        key: ${{ runner.os }}-nx-${{ hashFiles('**/nx.json') }}
        restore-keys: |
          ${{ runner.os }}-nx-

    - name: Build project
      id: build
      run: |
        echo "Building ${{ inputs.project-name }} at ${{ inputs.project-path }}"
        
        # Build the project using Nx
        npx nx build ${{ inputs.project-name }} --configuration=${{ inputs.build-configuration }}
        
        if [ $? -eq 0 ]; then
          echo "Build successful"
          echo "success=true" >> $GITHUB_OUTPUT
          
          # Set artifacts path if publishing
          if [ "${{ inputs.publish }}" = "true" ]; then
            echo "artifacts-path=${{ inputs.project-path }}/bin/${{ inputs.build-configuration }}/net8.0/publish" >> $GITHUB_OUTPUT
          else
            echo "artifacts-path=${{ inputs.project-path }}/bin/${{ inputs.build-configuration }}/net8.0" >> $GITHUB_OUTPUT
          fi
        else
          echo "Build failed"
          echo "success=false" >> $GITHUB_OUTPUT
          exit 1
        fi

    - name: Upload build artifacts
      if: inputs.publish == 'true' && steps.build.outputs.success == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.project-name }}-artifacts
        path: ${{ steps.build.outputs.artifacts-path }}
        retention-days: 7 