name: Generate Summary

on:
  workflow_call:
    inputs:
      title:
        description: 'Title for the summary'
        required: true
        type: string
      jobs:
        description: 'JSON array of job names to check'
        required: true
        type: string
      additional-content:
        description: 'Additional content to append to summary'
        required: false
        type: string
        default: ''

jobs:
  summary:
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate summary
      run: |
        echo "## ${{ inputs.title }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Parse jobs from input
        jobs='${{ inputs.jobs }}'
        
        # Check each job result
        for job in $(echo "$jobs" | jq -r '.[]'); do
          if [ "${{ needs.$job.result }}" = "success" ]; then
            echo "✅ $job passed" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ needs.$job.result }}" = "failure" ]; then
            echo "❌ $job failed" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️  $job was skipped" >> $GITHUB_STEP_SUMMARY
          fi
        done
        
        # Add additional content if provided
        if [ -n "${{ inputs.additional-content }}" ]; then
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "${{ inputs.additional-content }}" >> $GITHUB_STEP_SUMMARY
        fi 