name: Setup Environment
description: Setup Node.js, .NET, and dependencies for .NET projects with Nx
inputs:
  dotnet-version:
    description: .NET version to use
    required: false
    default: '8.0.x'
  node-version:
    description: Node.js version to use
    required: false
    default: '18'
runs:
  using: composite
  steps:
    - name: Load workflow configuration
      id: config
      uses: ./.github/actions/load-config

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version || steps.config.outputs.dotnet-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version || steps.config.outputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Restore .NET dependencies
      shell: bash
      run: npx nx g @nx-dotnet/core:restore

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Cache Nx
      uses: actions/cache@v4
      with:
        path: .nx/cache
        key: ${{ runner.os }}-nx-${{ hashFiles('**/nx.json') }}
        restore-keys: |
          ${{ runner.os }}-nx- 