name: CD - Deploy to Environments

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      app-name:
        description: 'Specific app to deploy (leave empty for all)'
        required: false
        type: string

jobs:
  # Load workflow configuration
  load-config:
    runs-on: ubuntu-latest
    outputs:
      dotnet-version: ${{ steps.config.outputs.dotnet-version }}
      build-configuration: ${{ steps.config.outputs.build-configuration }}
      staging-environment: ${{ steps.config.outputs.staging-environment }}
      production-environment: ${{ steps.config.outputs.production-environment }}
      main-branch: ${{ steps.config.outputs.main-branch }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Load workflow configuration
      id: config
      uses: ./.github/actions/load-config

  # Job to determine what to deploy (for automatic deployments)
  # Job to determine what to deploy (for automatic deployments)
  detect-changes:
    if: github.event_name != 'workflow_dispatch'
    uses: ./.github/workflows/templates/detect-changes.yml
    with:
      base-branch: 'main'
      head-branch: 'HEAD'

  # Job to determine what to deploy (for manual deployments)
  determine-deployment:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.get-affected.outputs.has-changes }}
      matrix: ${{ steps.get-affected.outputs.matrix }}
      affected-projects: ${{ steps.get-affected.outputs.affected-projects }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup environment
      uses: ./.github/actions/setup-environment

    - name: Get affected projects
      id: get-affected
      run: |
        # For manual dispatch, use the specified app or all apps
        if [ -n "${{ github.event.inputs.app-name }}" ]; then
          # Specific app deployment
          echo "Manual deployment for ${{ github.event.inputs.app-name }}"
          echo "has-changes=true" >> $GITHUB_OUTPUT
          echo "affected-projects=${{ github.event.inputs.app-name }}" >> $GITHUB_OUTPUT
          
          # Create matrix for specific app
          matrix='{"include":[{"name":"${{ github.event.inputs.app-name }}","path":"apps/${{ github.event.inputs.app-name }}","type":"webapi"}]}'
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
        else
          # Deploy all apps
          echo "Manual deployment for all apps"
          echo "has-changes=true" >> $GITHUB_OUTPUT
          echo "affected-projects=EchoAPI" >> $GITHUB_OUTPUT
          
          matrix='{"include":[{"name":"EchoAPI","path":"apps/EchoAPI","type":"webapi"}]}'
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
        fi

  # Consolidate deployment outputs
  consolidate-deployment:
    needs: [load-config, detect-changes, determine-deployment]
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.consolidate.outputs.has-changes }}
      matrix: ${{ steps.consolidate.outputs.matrix }}
      affected-projects: ${{ steps.consolidate.outputs.affected-projects }}
    
    steps:
    - name: Consolidate outputs
      id: consolidate
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "has-changes=${{ needs.determine-deployment.outputs.has-changes }}" >> $GITHUB_OUTPUT
          echo "matrix=${{ needs.determine-deployment.outputs.matrix }}" >> $GITHUB_OUTPUT
          echo "affected-projects=${{ needs.determine-deployment.outputs.affected-projects }}" >> $GITHUB_OUTPUT
        else
          echo "has-changes=${{ needs.detect-changes.outputs.has-changes }}" >> $GITHUB_OUTPUT
          echo "matrix=${{ needs.detect-changes.outputs.matrix }}" >> $GITHUB_OUTPUT
          echo "affected-projects=${{ needs.detect-changes.outputs.affected-projects }}" >> $GITHUB_OUTPUT
        fi

  # Build all projects for deployment
  build-for-deployment:
    needs: consolidate-deployment
    if: needs.consolidate-deployment.outputs.has-changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.consolidate-deployment.outputs.matrix) }}
      fail-fast: false
    
    steps:
    - name: Build ${{ matrix.project.name }} for deployment
      uses: ./.github/workflows/templates/build-dotnet.yml
      with:
        project-name: ${{ matrix.project.name }}
        project-path: ${{ matrix.project.path }}
        project-type: ${{ matrix.project.type }}
        dotnet-version: ${{ needs.load-config.outputs.dotnet-version }}
        build-configuration: ${{ needs.load-config.outputs.build-configuration }}
        publish: true

  # Deploy to staging environment
  deploy-staging:
    needs: [consolidate-deployment, build-for-deployment]
    if: |
      needs.consolidate-deployment.outputs.has-changes == 'true' && 
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging' || github.event_name == 'push')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.consolidate-deployment.outputs.matrix) }}
      fail-fast: false
    
    steps:
    - name: Deploy ${{ matrix.project.name }} to staging
      uses: ./.github/workflows/templates/deploy-app.yml
      with:
        app-name: ${{ matrix.project.name }}
        app-path: ${{ matrix.project.path }}
        environment: ${{ needs.load-config.outputs.staging-environment }}
        deployment-type: azure-app-service
        artifacts-name: ${{ matrix.project.name }}-artifacts
      secrets:
        azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

  # Deploy to production (manual approval required)
  deploy-production:
    needs: [consolidate-deployment, build-for-deployment, deploy-staging]
    if: |
      needs.consolidate-deployment.outputs.has-changes == 'true' && 
      github.event_name == 'workflow_dispatch' && 
      github.event.inputs.environment == 'production'
    runs-on: ubuntu-latest
    environment: ${{ needs.load-config.outputs.production-environment }}
    strategy:
      matrix:
        project: ${{ fromJson(needs.consolidate-deployment.outputs.matrix) }}
      fail-fast: false
    
    steps:
    - name: Deploy ${{ matrix.project.name }} to production
      uses: ./.github/workflows/templates/deploy-app.yml
      with:
        app-name: ${{ matrix.project.name }}
        app-path: ${{ matrix.project.path }}
        environment: ${{ needs.load-config.outputs.production-environment }}
        deployment-type: azure-app-service
        artifacts-name: ${{ matrix.project.name }}-artifacts
      secrets:
        azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

  # Deployment summary
  deployment-summary:
    needs: [consolidate-deployment, build-for-deployment, deploy-staging, deploy-production]
    uses: ./.github/workflows/templates/generate-summary.yml
    with:
      title: 'Deployment Summary'
      jobs: '["consolidate-deployment", "build-for-deployment", "deploy-staging", "deploy-production"]'
      additional-content: |
        if [ "${{ needs.consolidate-deployment.outputs.has-changes }}" = "true" ]; then
          echo "### Deployed Projects" >> $GITHUB_STEP_SUMMARY
          echo "${{ needs.consolidate-deployment.outputs.affected-projects }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          echo "### Build Results" >> $GITHUB_STEP_SUMMARY
          if [ "${{ needs.build-for-deployment.result }}" = "success" ]; then
            echo "✅ All builds successful" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Some builds failed" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.environment }}" = "production" ]; then
            echo "### Production Deployment" >> $GITHUB_STEP_SUMMARY
            if [ "${{ needs.deploy-production.result }}" = "success" ]; then
              echo "✅ Production deployment successful" >> $GITHUB_STEP_SUMMARY
            else
              echo "❌ Production deployment failed" >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "### Staging Deployment" >> $GITHUB_STEP_SUMMARY
            if [ "${{ needs.deploy-staging.result }}" = "success" ]; then
              echo "✅ Staging deployment successful" >> $GITHUB_STEP_SUMMARY
            else
              echo "❌ Staging deployment failed" >> $GITHUB_STEP_SUMMARY
            fi
          fi
        else
          echo "No changes detected. No deployment needed." >> $GITHUB_STEP_SUMMARY
        fi 